# NumPy Basics: Arrays and Vectorized Computation
# NumPy基础：数组和矢量计算

In [1]:
%matplotlib inline

In [3]:
from __future__ import division
from numpy.random import randn
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%cd ../book_scripts

[Error 2] : u'../book_scripts'
C:\Users\Administrator\pydata-book-master


## The NumPy ndarray: a multidimensional array object
## NumPy的ndarray：一种多维数组对象

In [41]:
data = randn(2,3,4) 
# python2.7适用，3.6则需要np.matlib.randn()
# 2个中括号，每个中括号里面有3行，每个行里面有4列（或者4个元素）
data = randn(2,3) 

In [42]:
data
data * 10
data + data

array([[ 2.3435, -3.3143,  0.8224],
       [ 2.4472,  0.6639, -1.5606]])

In [40]:
data.shape
data.dtype
#plt.plot(data)

dtype('float64')

### Creating ndarrays
### 创建ndarrays ，np.array

In [43]:
data1 = [6, 7.5, 8, 0, 1] #建立一个list 
arr1 = np.array(data1)    #把这个list传入Numpy素组（接受一切序列性对象）
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [44]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] #建立一个等长list组成的list 
arr2 = np.array(data2)               #np.array会把它变成是一个多维数组
arr2
#arr2.ndim
#arr2.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
arr1.dtype
arr2.dtype

dtype('int32')

In [46]:
np.zeros(10)      #其他可以创建数组的函数，全0值数组函数zeros()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [47]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [48]:
np.empty((2, 3, 2))        #其他可以创建数组的函数，一些未初始化的垃圾值数组函数empty()

array([[[ 0.9307, -0.1918],
        [ 0.95  ,  0.9525],
        [ 1.4843,  0.6649]],

       [[-1.0245, -0.7574],
        [-1.2202,  1.246 ],
        [ 1.9387, -1.5139]]])

In [49]:
np.arange(15)    #arange是Python内置函数range的数组版

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr000 = np.ones(10)
arr000

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
arr000.dtype

dtype('float64')

In [57]:
arr001 = np.eye(10)      #对角线为1，其余为0的【单位矩阵】
arr001

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

### Data Types for ndarrays
### ndarrays的数据类型 ， P86 i1,i2,i3,i4 / f2,f4,f8,f16,f128 / c8 c16 / bool / object / string_ / unicode_ 

In [6]:
arr1 = np.array([1, 2, 3], dtype=np.float64)  #dtype是个特殊对象，它含有ndarray将一块内存解释为特定数据类型所需的信息
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
#arr2.dtype

dtype('float64')

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype 


dtype('int32')

In [8]:
float_arr = arr.astype(np.float64)   # 可以使用astpye显式转换成dtype
float_arr.dtype

dtype('float64')

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])   #浮点数-->整型，小数部分会被截断。
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [9]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) #string_固定长度的字符串类型，每个字符串长度1个字节
numeric_strings

array(['1.25', '-9.6', '42'], 
      dtype='|S4')

In [10]:
numeric_strings.astype(float)   # 可以使用astpye显式转换成dtype

array([  1.25,  -9.6 ,  42.  ])

In [11]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
int_array.astype(calibers.dtype)  #这里int_array动态调运calibers.dtype的数据类型float64，但本质上其还是整型。参见In[13]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [13]:
int_array.dtype  # int_array的数据类型还是int32

dtype('int32')

In [14]:
empty_uint32 = np.empty(8, dtype='u4')  #dtype简洁表示法，记得要加‘’哦。 ‘u4'是unit32，即无符号32位整型，4个字节。
empty_uint32

array([1778384901,    6553601,      91136, 2197815908,   39452929,
           222208,   31226707,          0], dtype=uint32)

### Operations between arrays and scalars
### 数组与标量之间进行运算 
#### 数组很重要，因为可以不用编写循环即可对数据 (元素) 执行批量操作。这就叫“矢量化”
#### 大小不同的数组之间的运算叫做【广播】

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [19]:
arr * arr


array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [20]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
1 / arr


array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [23]:
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic indexing and slicing
### 基本的索引和切片

In [4]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [10]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [11]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [12]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0][2]
arr2d[0, 2]
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d.shape

(2L, 2L, 3L)

In [19]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3d[0,1]

array([4, 5, 6])

In [20]:
arr3d[0,1,0]

4

In [22]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d


array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[1, 0]

array([7, 8, 9])

#### Indexing with slices
#### 切片索引

In [25]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2, 1:]   #它是沿着axis0 切片的，沿着一个轴向选取元素。可以一次传入多个切片。前一个沿着axis0切，后一个沿着axis1切。

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[1, :2]    #整数索引+ 切片，可以得到低维度的切片。结果就是，从2维变成1维了。

array([4, 5])

In [29]:
arr2d[2, :1]

array([7])

In [31]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [33]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean indexing
### 布尔型索引

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
names
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'
data[-(names == 'Bob')]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### Fancy indexing

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

### Transposing arrays and swapping axes

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
    np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))